### PR TITLE
perf: add compatibility with nutmeg release

### PR DESCRIPTION
**Pull request by Henrrypg**
This PR is to add compatibility with nutmeg release

## How to test

You can run this strain:

```
STRAIN_NAME: nutmeg
STRAIN_TUTOR_VERSION: v14.0.5
DEV_PROJECT_NAME: nutmeg_dev
LOCAL_PROJECT_NAME: nutmeg_local
CMS_HOST: studio.nutmeg.edunext.link
LMS_HOST: lms.nutmeg.edunext.link
PLATFORM_NAME: Distro nutmeg
STRAIN_TUTOR_PLUGINS:
  - REPO: tutor-contrib-edunext-distro
    VERSION: v3.0.0-rc1
    EGG: tutor-contrib-edunext-distro==v3.0.0-rc1
    PACKAGE_NAME: distro
    PROTOCOL: ssh
  - REPO: tutor-forum
    VERSION: v14.0.0
    EGG: tutor-forum==v14.0.0
    PATH: overhangio
    PACKAGE_NAME: forum
STRAIN_EXTRA_COMMANDS:
  - APP: 'tutor'
    COMMAND: 'distro enable-themes'
STRAIN_VOLUME_OVERRIDES:
  edxapp:
    - DESTINATION: ../../src/edxapp/edx-platform
      LOCATION: /openedx/edx-platform
    - DESTINATION: ../../src/edxapp/eox-core
      LOCATION: /openedx/extra_deps/eox-core
    - DESTINATION: ../../src/edxapp/eox-tagging
      LOCATION: /openedx/extra_deps/eox-tagging
STRAIN_EXPORT_VOLUMES:
  - CONTAINER: lms
    LOCATION: /openedx/edx-platform
    DESTINATION: src/edxapp/edx-platform
  - CONTAINER: lms
    LOCATION: /openedx/extra_deps/eox-core
    DESTINATION: src/edxapp/eox-core
  - CONTAINER: lms
    LOCATION: /openedx/extra_deps/eox-tagging
    DESTINATION: src/edxapp/eox-tagging
DISTRO_EOX_CORE_DPKG:
  index: git
  name: eox-core
  private: false
  repo: eox-core
  domain: github.com
  path: eduNEXT
  protocol: https
  variables:
    development: {}
    production: {}
  version: mfmz/compatible-with-nutmeg
DISTRO_EOX_TAGGING_DPKG:
  index: git
  name: eox-tagging
  private: false
  repo: eox-tagging
  domain: github.com
  path: eduNEXT
  protocol: https
  variables:
    development: {}
    production: {}
  version: DS-253
```

with:

```
stack strain create
stack strain dev configure -k export_vols -k override_vols
stack strain dev init
stack strain dev configure -s export_vols -s override_vols
stack strain dev start
```

Then you can follow [test cases](https://docs.google.com/document/d/1VnjGF6Ri1Bvgbcd8AulM5jt68U7BmYJLVV2H5Bi5VOg/edit#heading=h.gcaxh6e3de55)

### CODE REVIEW

**Comment by MaferMazu** [comment]
@Henrrypg can you add some description in the PR and add python 3.10 support? Openedx-events is not a requirement and I think you can add Python 3.10. Please correct me if I am wrong 😊🙌

**Review by MaferMazu — APPROVED** [review]
Please update the PR title and description before the merge 😊

**Comment by Henrrypg** [comment]
> Please update the PR title and description before the merge blush

@MaferMazu Thank you, This PR is draft for now, the idea is working with this branch to complete the entire migration, for this reason so far I have not added desription

**Review by dcoa — APPROVED** [review]

**Comment by MaferMazu** [comment]
This PR takes into account all the steps of the migration, the only thing is that I still need to try the test cases, but I have had problems with the postman collection to test. So if someone else has already tried the test case and it works, that's fine with me; otherwise, when I can import the collection, I'll test the test cases.

**Comment by Henrrypg** [comment]
> This PR takes into account all the steps of the migration, the only thing is that I still need to try the test cases, but I have had problems with the postman collection to test. So if someone else has already tried the test case and it works, that's fine with me; otherwise, when I can import the collection, I'll test the test cases.

Hello @MaferMazu the Jira card in updated with de correct postman json, @dcoa  and @dsg-edn  already tested the test cases.

**Pull request merged**
