### PR TITLE
feat(DS-369): add compatibility with Open edX olive release

### PR DESCRIPTION
**Pull request by JuanDavidBuitrago**
## Description

This PR adds support for the Open edx olive release. Adds issue templates.

## Testing instructions

1. Create an environment with Olive release, you can use [Tutor](https://docs.tutor.overhang.io/index.html) or [TVM](https://github.com/eduNEXT/tvm)
2. Install the Django plugin eox-tagging, you can use steps in [Tutor documentation](https://docs.tutor.overhang.io/configuration.html#installing-extra-xblocks-and-requirements).
3. Run [test cases](https://docs.google.com/document/d/1VnjGF6Ri1Bvgbcd8AulM5jt68U7BmYJLVV2H5Bi5VOg/edit?usp=sharing) 

## Checklist for Merge

- [ ] Tested in a remote environment
- [ ] Updated documentation
- [ ] Rebased master/main
- [ ] Squashed commits

### CODE REVIEW

**Comment by JuanDavidBuitrago** [comment]
I tried to add support to Python 3.11, but found many problems. Mostly by some libraries that are no longer supported in some versions.

**Comment by dcoa** [comment]
I tested it and 90% of the things work well, my failed test cases are:

1. Can't create tags from swagger, when I press the button "Execute" nothing happens. 

2. Using postman the endpoint "Create by owner type" not works, first the tag definition isn't in the test case documentation
```json
     {
        "access": "public",
        "owner_object": "site",
        "tag_type": "subscription_level_user",
        "validate_target_object": "user"
    },
```
I add the definition and then the response was:
```json
{
    "Tag": "EOX_TAGGING | The field 'owner_object' must be equal to 'site'."
}
```
Do you know what I'm doing wrong?

3.  When I execute the Get tags by enrollment, the response includes all tags with target_id equal to `username` or `course_id` not only the `CourseEnrollment` target_type. I understand this happens due to this line https://github.com/eduNEXT/eox-tagging/blob/master/eox_tagging/api/v1/filters.py#L99  just want to confirm, is this the expected behavior?

**Comment by mariajgrimaldi** [comment]
I remembered I had this old postman collection which was the one I used while testing, in case someone else is interested:
[eox-tagging REST API.postman_collection.zip](https://github.com/eduNEXT/eox-tagging/files/10687541/eox-tagging.REST.API.postman_collection.zip)
All tests there with owner type site passed :)

**Comment by mariajgrimaldi** [comment]
@JuanDavidBuitrago: I have not found the cause of this weird swagger behavior. Could you please build an image so we can test this remotely? Thanks!

**Comment by MaferMazu** [comment]
I didn't use much swagger, but I don't know if this problem is related to not having the swagger schema like in [eox-core](https://github.com/eduNEXT/eox-core/blob/0a8016840d550c108eda48b3050777d156c4cc96/eox_core/api/v1/serializers.py#L335) or maybe its because the platform upgrade drf-yasg from 1.20.0 to 1.21.4, but I didn't see something [weird](https://github.com/axnsan12/drf-yasg/releases).

**Comment by JuanDavidBuitrago** [comment]
> @JuanDavidBuitrago: I have not found the cause of this weird swagger behavior. Could you please build an image so we can test this remotely? Thanks!

@mariajgrimaldi I created a ``olive-tagging`` image and make push to DockerHub. Could you help me test remotely? :smiley:

**Comment by mariajgrimaldi** [comment]
@JuanDavidBuitrago: I tested it, and as we supposed, it's still failing. I'll create an issue with the current information so we can tackle it later.

**Review by mariajgrimaldi — APPROVED** [review]
These changes look good! You're not updating to versions not supported already by the platform, so I don't believe this PR is related to the swagger behavior. We'll have to research more about what's happening with swagger in olive. I opened [an issue](https://github.com/eduNEXT/eox-tagging/issues/99) to keep track of the progress.

**Comment by JuanDavidBuitrago** [comment]
> These changes look good! You're not updating to versions not supported already by the platform, so I don't believe this PR is related to the swagger behavior. We'll have to research more about what's happening with swagger in olive. I opened [an issue](https://github.com/eduNEXT/eox-tagging/issues/99) to keep track of the progress.

Thanks for your help @mariajgrimaldi!!!

**Review by dcoa — APPROVED** [review]
I'm going to approve this PR understanding that now all the request via postman works.

Just left the message to verify the CurseEnrrollment get filter.

**Pull request merged**
